name: Create release

on: [ pull_request, workflow_dispatch ]

env:
  JAVA_VERSION: 17
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  #  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "${{env.JAVA_VERSION}}"
          distribution: 'temurin'

      - name: Build
        run: ./gradlew clean build

      - name: Publish Github/Modrinth
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          version-type: alpha
          changelog-file: CHANGELOG.md
          java: "${{env.JAVA_VERSION}}"

          github-token: "${{env.GITHUB_TOKEN}}"

          modrinth-id: ktCc1lQm
          modrinth-token: "${{env.MODRINTH_TOKEN}}"