# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Create release

on: [ pull_request, workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.19.3
  JAVA_VERSION: 17
  VERSION: 0.1.0+1.19.3-alpha6
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  #  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth/Github)
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          #        curseforge-id: 123456
          #        curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: final-stand
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          github-tag: "${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "Final Stand ${{env.VERSION}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
